//
//  LegalPersonPicker.swift
//  Financer
//
//  Created by Julian Schumacher on 24.12.22.
//

import SwiftUI
import CoreData

/// The View to pick a legal Person
/// for a single Finance
internal struct LegalPersonPicker: View {
    
    // Preview Code Start
    // (Comment to build)
    //
    // This Code is used in development because it works with the preview.
    // Solution from: https://developer.apple.com/forums/thread/654126
    
    /// The Finances fetched from
    /// the Core Database
    @FetchRequest(fetchRequest: legalPersonFetchRequest)
    private var legalPersons : FetchedResults<LegalPerson>
    
    /// This is the fetch Request to fetch all the Finances
    /// from the Core Data Persistence Storage
    static private var legalPersonFetchRequest : NSFetchRequest<LegalPerson> {
        let request = LegalPerson.fetchRequest()
        request.sortDescriptors = [
            NSSortDescriptor(
                keyPath: \LegalPerson.name,
                ascending: false
            )
        ]
        return request
    }
    // Preview Code End
    
    
    // Production Code Start
    // (Uncomment to build)
    //
    // This Code is used in production, becasue this Code
    // is generated by Apple and it is shorter.
    // This just doesn't work with the Preview
    
    /// The Finances fetched form the
    /// Code Database.
    //    @FetchRequest(
    //        sortDescriptors: [
    //            SortDescriptor(\LegalPerson.name, order: .reverse)
    //        ]
    //    ) private var legalPersons : FetchedResults<LegalPerson>
    // Production Code End
    
    /// The Type this View currently represents
    @State private var legalPersonType : LegalPerson.LegalPersonType = .none
    
    /// The Legal Person beeing chosen
    @Binding internal var legalPerson : LegalPerson?
    
    var body: some View {
        VStack {
            Picker("Type", selection: $legalPersonType) {
                ForEach(LegalPerson.LegalPersonType.allCases)
            }
            NavigationLink {
                AddLegalPerson()
            } label: {
                Label("Add Legal Person", systemImage: "plus")
            }
        }
        .navigationTitle("Legal Person Picker")
    }
}

internal struct LegalPersonPicker_Previews: PreviewProvider {
    /// The Preview Legal Person
    @State static private var lP : LegalPerson? = {
        let context = PersistenceController.preview.container.viewContext
        let person = Person(context: context)
        person.name = "Test Person"
        return person
    }()
    
    static var previews: some View {
        LegalPersonPicker(legalPerson: $lP)
    }
}
